# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hashnode-activity-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: ap-south-1
  environment:
    HASHNODE_PASSWORD: ${env:HASHNODE_PASSWORD}
    


package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables


functions:
  create-post:
    handler: apis/posts/create.main
    events:
      - http:
          path: /post
          method: post
          cors: true
  get-post:
    handler: apis/posts/get.main
    events:
      - http:
          path: /post/{id}
          method: get
          cors: true
  get-activities:
    handler: apis/activity/get.main
    events:
      - http:
          path: /activities
          method: get
          cors: true
  create-comment:
    handler: apis/comments/create.main
    events:
      - http:
          path: /comment
          method: post
          cors: true
  get-comments:
    handler: apis/comments/get.main
    events:
      - http:
          path: /comments
          method: post
          cors: true

		